### ISSUE TITLE
Send sam list of software options

### ISSUE THREAD

**Issue by antiboredom** [nycdoe-cs4all/blueprint-learning-site#21]
Processing, scratch, etc.

**Comment by aankit** [comment]
Scratch (Web)
Repl.it
Trinket
Pencil Code
Pyret
CodePen
Thimble
p5
Snap!
AppInventor
Other Web Application
Scratch (Desktop)
Lego EV3/NXT
Processing
Arduino
PyCharm
Alice
AppInventor Mobile Emulator
Other Desktop Application
Scratch Jr.
Kodables
The Foos
Tynker
HopScotch
Other Mobile Application
