### ISSUE TITLE
Create "Resources"

### ISSUE THREAD

**Issue by antiboredom** [nycdoe-cs4all/blueprint-learning-site#24]
- link to resources in top nav
- admins can:
 - create/edit/delete resources
 - when creating, option  to import from google docs
 - connect them to activities

Resources have categories
- "For teachers", "For administrators"

**Comment by aankit** [comment]
"For teachers" and "For administrators" not relevant. 

Resources should be tagged.

**Comment by antiboredom** [comment]
Link to related units on resource page

**Comment by antiboredom** [comment]
option to connect resources to particular units or ALL units

**Comment by antiboredom** [comment]
add rich text editor

**Comment by antiboredom** [comment]
OK - I think I've implemented all of this!

**Comment by antiboredom** [comment]
Hey - you can - it's just that the only two tags are "for administrators" and "for teachers" - but you can add other tags from the admin panel.

**Comment by antiboredom** [comment]
To fix:
- remove tags from nav
- put all tags in sidebar on resource page
