### ISSUE TITLE
Decide Filter categories for search page

### ISSUE THREAD

**Issue by nycdoe-cs4all** [nycdoe-cs4all/blueprint-learning-site#4]
- Grade
- Subject
- Depth of Knowledge Level (this may not be a filter)
- Devices Needed

**Comment by aankit** [comment]
Add:

- Concept (checkbox)
   - Abstraction
   - Algorithms
   - Programming
   - Data & Information
   - Networks

- Software
  - Chrome
  - Firefox
  - Other Browser
  - Desktop Application
  - Mobile Application

**Comment by aankit** [comment]
Add: Pacing in hours and minutes

Remove "Levels" - everything is going to be a unit which hits all the levels.
