### ISSUE TITLE
conflicts b/w site css and "upload from google docs" feature

### ISSUE THREAD

**Issue by juliaem** [nycdoe-cs4all/blueprint-learning-site#47]
CSS is not uniformly applying to the resource pages, where content was uploaded from a Google doc.

Example: 
http://blueprint.cs4all.nyc/resources/8/ 
vs. http://blueprint.cs4all.nyc/resources/7/

**Comment by aankit** [comment]
@antiboredom Looking at the resources that are imported from google docs, I'm seeing inline style still in the HTML, which might be causing this problem. This is the resource that I'm looking at: http://blueprint.cs4all.nyc/resources/3/

**Comment by juliaem** [comment]
One more factor which might be contributing-- the upload hasn't been working so great, so sometimes I copy and paste rather than use the import...

**Comment by aankit** [comment]
related to #56
