### ISSUE TITLE
Links in Google Docs give users redirect notice

### ISSUE THREAD

**Issue by aankit** [nycdoe-cs4all/blueprint-learning-site#60]
When a hyperlink is put in a Google Doc and that Google Doc is imported those links looks like this:

https://www.google.com/url?q=[URL]

All links follow the same format. Can we strip these part out of links when importing them?

**Comment by antiboredom** [comment]
can you post an example url for me to play with?

**Comment by aankit** [comment]
https://www.google.com/url?q=http://scratched.gse.harvard.edu/ct/files/CT_Practices_Journal.pdf&sa=D&ust=1500851459419000&usg=AFQjCNEfWKriI5e0ZGPoqD6GPADSz-6lkQ

It's a URL in this resource: http://blueprint.cs4all.nyc/resources/11/

**Comment by aankit** [comment]
http://blueprint.cs4all.nyc/resources/21/
https://docs.google.com/document/d/107lMRU2Y2IaseNOkc4RNEcEDn1XpIN-E97ThtQBgZx0/edit

This resource has links in it that have a lot of junk at the end that results in links not working. I'm not sure this is working yet...

**Comment by aankit** [comment]
here are example links: 

https://www.meetup.com/CSNYC-Education-Meetup/&sa=D&ust=1501176742827000&usg=AFQjCNHu245q-oecTshYoLSeeyBsLGqkmQ

https://www.meetup.com/ScratchEd-New-York/&sa=D&ust=1501176742827000&usg=AFQjCNGVxuWs8gyoxZDuBHVYdcb8G8i6lQ

**Comment by aankit** [comment]
@antiboredom can you take care of this before 8/10?

**Comment by ritammehta** [comment]
Update: this has been fixed for resources. However, it seems that the resource google doc import doesn't use the same chunk of code as the unit google doc import function. This issue exists with both and needs to be updated for both.

**Comment by aankit** [comment]
closing this for now since I don't think we are seeing this issue with units or resources. Not sure I understand the comment about different import functions for resources vs units, but we can start a different issue for that later.
