### ISSUE TITLE
Cannot submit new units

### ISSUE THREAD

**Issue by aankit** [nycdoe-cs4all/blueprint-learning-site#61]
Trying to add this unit to the site right now and it doesn't seem to be working. I've tried changing permissions on the Google doc to public and that didn't change anything.

https://docs.google.com/document/d/1vwwctuaGK5QDERHnLglC9lLMEiZvoz83BL1qWD-FQbw/edit#

**Comment by antiboredom** [comment]
can you try again?

**Comment by aankit** [comment]
works. 🙌
