### ISSUE TITLE
Kaho & Ramsey

### ISSUE THREAD

**Issue by cs4allnyc** [nycdoe-cs4all/blueprint-learning-site#65]
Why are we linking to their email? Do they have a site we could use instead?
http://blueprint.cs4all.nyc/units/25/

Redirect issues with every one of the links on their page. 
![screen shot 2017-07-28 at 8 34 44 am](https://user-images.githubusercontent.com/17147758/28717434-c53b9052-736f-11e7-8806-bcd00b6f5d1b.png)
https://www.google.com/url?q=http://nas.sr/sponge/pdf/diagonal-line.pdf&sa=D&ust=1501117680714000&usg=AFQjCNHwC8ktT1XWHiX6k2KvN-LnJH9JHA

**Comment by ritammehta** [comment]
@aankit what do you think? is this a separate problem to the one on the resource page or do we need to manually fix the unit links as well?

**Comment by aankit** [comment]
this is actually because their website is just a big picture of the two of
them - it's not a helpful site, that's why I'm linking to email.

**Comment by ritammehta** [comment]
fixed
