### ISSUE TITLE
HOW DO WE CREATE TEAMS AND BUY-IN TO SUPPORT CS ROLL OUT?

### ISSUE THREAD

**Issue by cs4allnyc** [nycdoe-cs4all/blueprint-learning-site#66]
The link for Scratch Days is linked to both words separately. Small nit-picky issue.

Once teachers and students have tried out CS concepts and practices, we’ve seen schools successfully host events celebrating the school’s achievements and encouraging broader participation in CS. Examples include “hackathons” in which students use their newly honed CS skills to build solutions to a set of challenges, “maker nights” in which teachers, students, and families come together to build physical computing projects, and Scratch Days in which students build games using Scratch. We’ve even seen pep rallies in which students wear their physical computing projects during dance performances.

**Comment by ritammehta** [comment]
Fixed!
