### ISSUE TITLE
Introduction to CS Lionel's Unit

### ISSUE THREAD

**Issue by cs4allnyc** [nycdoe-cs4all/blueprint-learning-site#70]
http://blueprint.cs4all.nyc/units/28/

Redirect errors on all links to external sites work
PDFs and google slides worked except this one you need to change the permissions:
Collect a variety of non-technology items (should be one per student and can be pictures.) **examples**: pencil, toothbrush, etc.

**Comment by ritammehta** [comment]
Related to #65
